version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven dependencies..."
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn package -DskipTests=true
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
